name: CI 
 
on: push 
 
jobs: 
  build: 
    runs-on: self-hosted 
    steps: 
      - name: descargar repostorio 
        uses: actions/checkout@v3 
      - name: pruebas-unitarias 
        run: mvn test 
      - name: compilar la aplicación sin repetir pruebas 
        run: mvn package -DskipTests=true  